# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-ABC-Archive
version:      0.02
version_from: Archive.pm
installdirs:  site
requires:
    Music::ABC::Song:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
